GIN_MODE: debug

POSTGRES_DB_HOST: localhost
POSTGRES_DB_USER: company_user
POSTGRES_DB_PASSWORD: company_pass
POSTGRES_DB_NAME: companydb
DB_SSL_MODE: disabled

REDIS_SERVER: localhost:6379

SERVER_PORT: 0.0.0.0:5000
